baseURL: "https://nadunnanayakkara.github.io/" 
title: Nadun Nanayakkara
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
          weight: 1
        - name: Experience
          url: experience/
          weight: 2
        - name: Education
          url: education/
          weight: 3
        - name: Projects
          url: projects/
          weight: 4

params:
    description: "Portfolio of Nadun Demiththa Nanayakkara – Junior Software Engineer & Graphic Designer from Sri Lanka. Passionate about web development, React, and cloud technologies."
    author: Nadun Demiththa Nanayakkara
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: false
    profileMode:
          enabled: true
          title: Nadun Demiththa Nanayakkara
          subtitle: "Junior Software Engineer & Graphic Designer | React · HTML/CSS/JS · AWS · MySQL | Passionate about building efficient, scalable, and innovative software solutions."
          imageUrl: "static/picture.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About Me
              url: about/
            - name: Experience
              url: experience/
            - name: Education
              url: education/
            - name: Projects
              url: projects/

    socialIcons:
        - name: CV
          url: nadun cv.pdf
        - name: Email
          url: nadunnanayakkara19@gmail.com
        - name: GitHub
          url: https://github.com/nadunnanayakkara
        - name: Location
          url: location/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Nadun Nanayakkara"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2